Add extra_options to checkedm calls
Added a config option to enable adding extra options to checkedm call.

Change-Id: Id3b13b57d10d98fcad4bb6418453229b8a1913b4
Addresses-Issue: Jira/AQUILON-2599
Reviewed-by: Dave Reeve <Dave.Reeve@morganstanley.com>

diff --git a/tests/fakebin/fake_checkedm b/tests/fakebin/fake_checkedm
--- a/tests/fakebin/fake_checkedm
+++ b/tests/fakebin/fake_checkedm
@@ -19,11 +19,21 @@ while [ -n "$1" ]; do
 			SYSTEM="$2"
 			shift
 			;;
+		--extra-option)
+			EXTOPT="$2"
+			shift
+			;;
 		*)
 		    ;;
 	esac
 	shift
 done
+
+if [ "x$EXTOPT" != "xapple_tree" ]
+then
+    echo "Missing or bad extra option $EXTOPT"
+    exit 1
+fi
 
 if [ $TICKET == "12345678" -a $SYSTEM == "TCM2" ]
 then
